name: Construcția manuală a documentației în format HTML
on:
  workflow_dispatch:
    inputs:
      ramuraLuiCPython:
        description: 'Ce ramură a depozitului CPython folosim?'
        required: true
        type: choice
        options:
          - '3.13'
          - 'v3.13.7' # versiunea stabila 3.13 (vezi https://github.com/python/cpython/releases/tag/v3.13.7)
          - '3.14'
          - 'latest'
jobs:
  constructia-traducerii:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - uses: actions/checkout@v5
        with: 
          repository: 'python/cpython'
          ref: ${{ inputs.ramuraLuiCPython }}
      - run: make venv
        working-directory: ./Doc
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ramuraLuiCPython }}
          path: Doc/locales/ro/LC_MESSAGES
      - run: git pull
        working-directory: ./Doc/locales/ro/LC_MESSAGES
      - run: make -e SPHINXOPTS="--color -D language='ro' -W --keep-going" html
        working-directory: ./Doc
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: build-${{ inputs.ramuraLuiCPython }}-html
          path: Doc/build/html
